#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "drupal7"
name = "Drupal 7"
description.en = "Old version of a content management framework written in PHP"
description.fr = "Ancienne version d'un système de gestion de contenu écrit en PHP"

version = "7.103~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.drupal.org"
userdoc = "https://www.drupal.org/docs/7"
code = "https://github.com/drupal/drupal"
cpe = "cpe:2.3:a:drupal:drupal"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/drupal7"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.install_profil]
    ask.en = "Choose the Drupal 7 install profile to use"
    ask.fr = "Choisissez le profile d'installation de Drupal 7"
    type = "select"
    choices = ["minimal", "standard"]
    default = "standard"

[resources]

    [resources.sources]

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-cli",
        "php8.3-gd",
        "php8.3-mysql",
        "php8.3-xml",
        "php8.3-ldap",
        "php8.3-mbstring",
        "php8.3-uploadprogress",
        "php8.3-apcu",
        "curl",
        "libzip-dev",
        "mariadb-server",
        ]

    [resources.database]
    type = "mysql"
