#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.install_profil = "minimal"

    test_upgrade_from.f4744174a13ab7247037783aafd3659226f4cb0a.name = "7.98~ynh1"
